debug

diff --git a/.github/workflows/template.terraform.validate.yml b/.github/workflows/template.terraform.validate.yml
--- a/.github/workflows/template.terraform.validate.yml
+++ b/.github/workflows/template.terraform.validate.yml
@@ -47,98 +47,98 @@ jobs:
         with:
           ref: ${{ inputs.branchName }}
 
-      - name: Setup Toolset
-        run: |
-          ./setup-azcli.sh
-          ./setup-gitleaks.sh
-          ./setup-terraform.sh ${{ inputs.terraformVersion }}
-          ./setup-tflint.sh
-          source ~/.bashrc
-        working-directory: scripts/orchestrators
+      # - name: Setup Toolset
+      #   run: |
+      #     ./setup-azcli.sh
+      #     ./setup-gitleaks.sh
+      #     ./setup-terraform.sh ${{ inputs.terraformVersion }}
+      #     ./setup-tflint.sh
+      #     source ~/.bashrc
+      #   working-directory: scripts/orchestrators
 
-      - name: Run Gitleaks
-        run: |
-          source ./scanners.sh
-          run_gitleaks './../../' 'sarif' 'info' 'true' 'true'
-        working-directory: scripts/orchestrators
+      # - name: Run Gitleaks
+      #   run: |
+      #     source ./scanners.sh
+      #     run_gitleaks './../../' 'sarif' 'info' 'true' 'true'
+      #   working-directory: scripts/orchestrators
 
-      - uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: gitleaks-report
-          path: scripts/orchestrators/gitleaks-report.*
+      # - uses: actions/upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     name: gitleaks-report
+      #     path: scripts/orchestrators/gitleaks-report.*
 
-      - name: Upload Gitleaks SARIF report to code scanning service
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: scripts/orchestrators/gitleaks-report.sarif
+      # - name: Upload Gitleaks SARIF report to code scanning service
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   with:
+      #     sarif_file: scripts/orchestrators/gitleaks-report.sarif
 
-      - name: Run TF Lint
-        env:
-          WORKSPACE_PATH: ${{ github.workspace }}
-        run: |
-          ./iac.tf.lint.sh
-        working-directory: scripts/orchestrators
-        shell: bash
+      # - name: Run TF Lint
+      #   env:
+      #     WORKSPACE_PATH: ${{ github.workspace }}
+      #   run: |
+      #     ./iac.tf.lint.sh
+      #   working-directory: scripts/orchestrators
+      #   shell: bash
 
-      - uses: azure/login@v2
-        name: Run Azure Login
-        with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+      # - uses: azure/login@v2
+      #   name: Run Azure Login
+      #   with:
+      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
+      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Get KeyVault Secret(s)
-        id: LoadSecrets
-        env:
-          SECRETS: "stateRg, stateContainer, stateStorageAccount"
-          KEY_VAULT_NAME: ${{ inputs.keyVaultName }}
-        run: ./github.loadsecrets.sh
-        working-directory: scripts/orchestrators
+      # - name: Get KeyVault Secret(s)
+      #   id: LoadSecrets
+      #   env:
+      #     SECRETS: "stateRg, stateContainer, stateStorageAccount"
+      #     KEY_VAULT_NAME: ${{ inputs.keyVaultName }}
+      #   run: ./github.loadsecrets.sh
+      #   working-directory: scripts/orchestrators
 
-      - name: Run TF Validate
-        env:
-          WORKSPACE_PATH: ${{ github.workspace }}
-          ENVIRONMENT_NAME: ${{ inputs.environmentName }}
-        run: |
-          export STATE_RG=${{ steps.LoadSecrets.outputs.stateRg }}
-          export STATE_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.stateStorageAccount }}
-          export STATE_CONTAINER=${{ steps.LoadSecrets.outputs.stateContainer }}
+      # - name: Run TF Validate
+      #   env:
+      #     WORKSPACE_PATH: ${{ github.workspace }}
+      #     ENVIRONMENT_NAME: ${{ inputs.environmentName }}
+      #   run: |
+      #     export STATE_RG=${{ steps.LoadSecrets.outputs.stateRg }}
+      #     export STATE_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.stateStorageAccount }}
+      #     export STATE_CONTAINER=${{ steps.LoadSecrets.outputs.stateContainer }}
 
-          ./iac.tf.validate.sh
-        working-directory: scripts/orchestrators
-        shell: bash
+      #     ./iac.tf.validate.sh
+      #   working-directory: scripts/orchestrators
+      #   shell: bash
 
-      - uses: actions/setup-go@v4
-        with:
-          go-version: ${{ inputs.goVersion }}
-      - name: Run Layer Tests
-        if: ${{ inputs.runLayerTest == 'true' }}
-        env:
-          WORKSPACE_PATH: ${{ github.workspace }}
-          ENVIRONMENT_NAME: ${{ inputs.environmentName }}
-          ENVIRONMENT_DIRECTORY: ${{ inputs.environmentDirectory }}
-          TEST_TAG: module_tests
-        run: |
-          export STATE_RG=${{ steps.LoadSecrets.outputs.stateRg }}
-          export STATE_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.stateStorageAccount }}
-          export STATE_CONTAINER=${{ steps.LoadSecrets.outputs.stateContainer }}
+      # - uses: actions/setup-go@v4
+      #   with:
+      #     go-version: ${{ inputs.goVersion }}
+      # - name: Run Layer Tests
+      #   if: ${{ inputs.runLayerTest == 'true' }}
+      #   env:
+      #     WORKSPACE_PATH: ${{ github.workspace }}
+      #     ENVIRONMENT_NAME: ${{ inputs.environmentName }}
+      #     ENVIRONMENT_DIRECTORY: ${{ inputs.environmentDirectory }}
+      #     TEST_TAG: module_tests
+      #   run: |
+      #     export STATE_RG=${{ steps.LoadSecrets.outputs.stateRg }}
+      #     export STATE_STORAGE_ACCOUNT=${{ steps.LoadSecrets.outputs.stateStorageAccount }}
+      #     export STATE_CONTAINER=${{ steps.LoadSecrets.outputs.stateContainer }}
 
-          ./iac.tf.test.sh
+      #     ./iac.tf.test.sh
 
-        working-directory: scripts/orchestrators
-        shell: bash
+      #   working-directory: scripts/orchestrators
+      #   shell: bash
 
-      - uses: actions/upload-artifact@v4
-        if: ${{ always() && inputs.runLayerTest == 'true' }}
-        with:
-          name: Modules test results
-          path: ./IAC/Terraform/test/terraform/*.xml
+      # - uses: actions/upload-artifact@v4
+      #   if: ${{ always() && inputs.runLayerTest == 'true' }}
+      #   with:
+      #     name: Modules test results
+      #     path: ./IAC/Terraform/test/terraform/*.xml
 
-      - name: Publish Module Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: ${{ inputs.runLayerTest == 'true' }}
-        with:
-          files: "./IAC/Terraform/test/terraform/*.xml"
-          check_name: "Modules tests Results"
-          action_fail: true
+      # - name: Publish Module Test Results
+      #   uses: EnricoMi/publish-unit-test-result-action@v2
+      #   if: ${{ inputs.runLayerTest == 'true' }}
+      #   with:
+      #     files: "./IAC/Terraform/test/terraform/*.xml"
+      #     check_name: "Modules tests Results"
+      #     action_fail: true
